name: Baselines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: baselines

jobs:
  test_baselines:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.12
      - name: Install build tools
        run: |
          python -m pip install -U pip==22.2
          python -m pip install -U setuptools==63.2.0
          python -m pip install -U poetry==1.1.14
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test.sh
