name: Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_core:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [3.7.12, 3.8.12, 3.9.10, 3.10.5]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install build tools
        run: |
          sudo apt-get install clang-format
          python -m pip install -U pip==22.2
          python -m pip install -U setuptools==63.2.0
          python -m pip install -U poetry==1.1.14
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --extras "simulation"
      - name: Check if protos need recompilation
        run: ./dev/check-protos.sh
      - name: Lint + Test (isort/black/docformatter/mypy/pylint/flake8/pytest)
        run: ./dev/test.sh
